[build]
  base = "/"       # Root directory where Netlify installs dependencies and runs the build command
  publish = "out"  # Directory where static files are output

[[plugins]]
  package = "@netlify/plugin-nextjs"
